import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "../styles/globals.css";
import StickySide from "@/components/sections/stickySide";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} bg-secondary text-primary flex flex-col-reverse xl:flex-row w-full min-h-screen`}>
        {children}
        <StickySide />
      </body>
    </html>
  );
}
